
version: '3.8'
services:
  accounts-service:
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8080:8080"
  
  products-service:
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8081:8081"
  
  orders-service:
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8082:8082"
