#!/usr/bin/env python3
"""
Backend environment setup script for Spring Boot microservices
Automatically detects if running in GitHub Codespaces and sets appropriate URLs
"""

import os
import shutil
import glob
import yaml

def setup_backend_environment():
    """Setup backend environment variables and configurations"""
    
    print("🔧 Setting up backend environment...")
    
    # Check if we're in GitHub Codespaces
    is_codespaces = os.getenv('CODESPACES') == 'true'
    codespace_name = os.getenv('CODESPACE_NAME')
    github_codespaces_port_forwarding_domain = os.getenv('GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN', 'preview.app.github.dev')
    
    # Create .env file for backend
    create_backend_env_file(is_codespaces, codespace_name, github_codespaces_port_forwarding_domain)
    
    # Update Spring Boot application configurations
    update_spring_configurations(is_codespaces, codespace_name, github_codespaces_port_forwarding_domain)
    
    print("✅ Backend environment setup complete!")

def create_backend_env_file(is_codespaces, codespace_name, github_domain):
    """Create/update backend .env file"""
    
    env_vars = {}
    
    if is_codespaces and codespace_name:
        print(f"🚀 Configuring backend for GitHub Codespaces: {codespace_name}")
        
        # Database URLs for Codespaces
        env_vars['DB_HOST'] = f"{codespace_name}-3306.{github_domain}"
        env_vars['DB_URL'] = f"jdbc:mysql://{codespace_name}-3306.{github_domain}/Game_Store_System?createDatabaseIfNotExist=true"
        env_vars['ENVIRONMENT'] = 'codespaces'
        
        # Service discovery URLs
        env_vars['ACCOUNTS_SERVICE_URL'] = f"https://{codespace_name}-8080.{github_domain}"
        env_vars['PRODUCTS_SERVICE_URL'] = f"https://{codespace_name}-8081.{github_domain}"
        env_vars['ORDERS_SERVICE_URL'] = f"https://{codespace_name}-8082.{github_domain}"
        env_vars['PAYMENTS_SERVICE_URL'] = f"https://{codespace_name}-8083.{github_domain}"
        env_vars['STOCK_SERVICE_URL'] = f"https://{codespace_name}-8084.{github_domain}"
        
    else:
        print("🏠 Configuring backend for local development")
        
        # Local database
        env_vars['DB_HOST'] = 'localhost:3306'
        env_vars['DB_URL'] = 'jdbc:mysql://localhost:3306/Game_Store_System?createDatabaseIfNotExist=true'
        env_vars['ENVIRONMENT'] = 'local'
        
        # Local service URLs
        env_vars['ACCOUNTS_SERVICE_URL'] = 'http://localhost:8080'
        env_vars['PRODUCTS_SERVICE_URL'] = 'http://localhost:8081'
        env_vars['ORDERS_SERVICE_URL'] = 'http://localhost:8082'
        env_vars['PAYMENTS_SERVICE_URL'] = 'http://localhost:8083'
        env_vars['STOCK_SERVICE_URL'] = 'http://localhost:8084'
    
    # Common configuration
    env_vars['DB_USERNAME'] = 'gamestore_user'
    env_vars['DB_PASSWORD'] = 'gamestore_pass'
    env_vars['YOUTUBE_API_KEY'] = 'AIzaSyA_cOSojH1AVc4phKoP14cYPkGUpdWhpuQ'
    env_vars['YOUTUBE_CHANNEL_ID'] = '@Ritrix252'
    
    # Write .env file
    with open('.env', 'w') as f:
        f.write("# Backend Environment Variables\n")
        f.write("# Auto-generated by setup_backend_env.py\n\n")
        
        f.write("# Database Configuration\n")
        f.write(f"DB_HOST={env_vars['DB_HOST']}\n")
        f.write(f"DB_URL={env_vars['DB_URL']}\n")
        f.write(f"DB_USERNAME={env_vars['DB_USERNAME']}\n")
        f.write(f"DB_PASSWORD={env_vars['DB_PASSWORD']}\n\n")
        
        f.write("# Service URLs\n")
        for key, value in env_vars.items():
            if '_SERVICE_URL' in key:
                f.write(f"{key}={value}\n")
        
        f.write(f"\n# Environment\n")
        f.write(f"ENVIRONMENT={env_vars['ENVIRONMENT']}\n")
        f.write(f"YOUTUBE_API_KEY={env_vars['YOUTUBE_API_KEY']}\n")
        f.write(f"YOUTUBE_CHANNEL_ID={env_vars['YOUTUBE_CHANNEL_ID']}\n")
    
    print(f"📍 Database: {env_vars['DB_HOST']}")

def update_spring_configurations(is_codespaces, codespace_name, github_domain):
    """Update Spring Boot application.yml files"""
    
    # Find all application.yml files
    yml_files = glob.glob("**/src/main/resources/application.yml", recursive=True)
    
    service_ports = {
        'accounts-service': 8080,
        'products-service': 8081,
        'orders-service': 8082,
        'payments-service': 8083,
        'stock-service': 8084,
        'wishlist-service': 8085,
        'orderItems-service': 8086,
        'customerSummary-service': 8087,
        'soldProducts-service': 8088,
        'purchasedProducts-service': 8089
    }
    
    for yml_file in yml_files:
        print(f"📝 Updating {yml_file}")
        update_application_yml(yml_file, is_codespaces, codespace_name, github_domain, service_ports)

def update_application_yml(file_path, is_codespaces, codespace_name, github_domain, service_ports):
    """Update individual application.yml file"""
    
    # Determine service name from path
    service_name = None
    for name in service_ports.keys():
        if name in file_path:
            service_name = name
            break
    
    if not service_name:
        return
    
    # Read current configuration
    try:
        with open(file_path, 'r') as f:
            config = yaml.safe_load(f) or {}
    except:
        config = {}
    
    # Ensure nested structure exists
    if 'spring' not in config:
        config['spring'] = {}
    if 'datasource' not in config['spring']:
        config['spring']['datasource'] = {}
    if 'server' not in config:
        config['server'] = {}
    
    # Set database configuration
    if is_codespaces and codespace_name:
        db_url = f"jdbc:mysql://{codespace_name}-3306.{github_domain}/Game_Store_System?createDatabaseIfNotExist=true"
    else:
        db_url = "jdbc:mysql://localhost:3306/Game_Store_System?createDatabaseIfNotExist=true"
    
    config['spring']['datasource'].update({
        'url': db_url,
        'username': 'gamestore_user',
        'password': 'gamestore_pass',
        'driver-class-name': 'com.mysql.cj.jdbc.Driver'
    })
    
    # Set server port
    config['server']['port'] = service_ports[service_name]
    
    # Add environment-specific profiles
    if 'profiles' not in config['spring']:
        config['spring']['profiles'] = {}
    
    if is_codespaces:
        config['spring']['profiles']['active'] = 'codespaces'
    else:
        config['spring']['profiles']['active'] = 'local'
    
    # Write updated configuration
    with open(file_path, 'w') as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)

def create_docker_compose_override():
    """Create docker-compose override for different environments"""
    
    is_codespaces = os.getenv('CODESPACES') == 'true'
    
    if is_codespaces:
        # Create Codespaces-specific override
        override_content = """
version: '3.8'
services:
  accounts-service:
    environment:
      - SPRING_PROFILES_ACTIVE=codespaces
    ports:
      - "8080:8080"
  
  products-service:
    environment:
      - SPRING_PROFILES_ACTIVE=codespaces
    ports:
      - "8081:8081"
  
  orders-service:
    environment:
      - SPRING_PROFILES_ACTIVE=codespaces
    ports:
      - "8082:8082"
"""
    else:
        # Create local development override
        override_content = """
version: '3.8'
services:
  accounts-service:
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8080:8080"
  
  products-service:
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8081:8081"
  
  orders-service:
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8082:8082"
"""
    
    with open('docker-compose.override.yml', 'w') as f:
        f.write(override_content)
    
    print(f"✅ Created docker-compose.override.yml for {'Codespaces' if is_codespaces else 'local'} environment")

if __name__ == "__main__":
    # Ensure we're in the backend directory
    if not os.path.exists('build.gradle'):
        print("❌ Please run this script from the backend directory")
        exit(1)
    
    setup_backend_environment()
    create_docker_compose_override()
