#!/bin/bash

# Backend environment setup script for Spring Boot microservices
# Automatically detects environment and configures database/service URLs

echo "🔧 Setting up backend environment for Spring Boot services..."

# Check if we're in the backend directory
if [ ! -f "build.gradle" ]; then
    echo "❌ Please run this script from the backend directory"
    exit 1
fi

# Service port mappings
declare -A service_ports=(
    ["accounts-service"]="8080"
    ["products-service"]="8081" 
    ["orders-service"]="8082"
    ["payments-service"]="8083"
    ["stock-service"]="8084"
    ["wishlist-service"]="8085"
    ["orderItems-service"]="8086"
    ["customerSummary-service"]="8087"
    ["soldProducts-service"]="8088"
    ["purchasedProducts-service"]="8089"
)

# Check if we're in GitHub Codespaces
if [ "$CODESPACES" = "true" ] && [ -n "$CODESPACE_NAME" ] && [ -n "$GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN" ]; then
    echo "🚀 Detected GitHub Codespaces environment: $CODESPACE_NAME"
    
    # Set Codespaces URLs
    DB_HOST="${CODESPACE_NAME}-3306.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
    DB_URL="jdbc:mysql://${DB_HOST}/Game_Store_System?createDatabaseIfNotExist=true"
    ENVIRONMENT="codespaces"
    
    echo "📍 Database Host: $DB_HOST"
    
    # Create .env file for Codespaces
    cat > .env << EOF
# Backend Environment Variables for Codespaces
# Auto-generated by setup_backend_env.sh

# Database Configuration
DB_HOST=$DB_HOST
DB_URL=$DB_URL
DB_USERNAME=gamestore_user
DB_PASSWORD=gamestore_pass

# Service URLs
ACCOUNTS_SERVICE_URL=https://${CODESPACE_NAME}-8080.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
PRODUCTS_SERVICE_URL=https://${CODESPACE_NAME}-8081.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
ORDERS_SERVICE_URL=https://${CODESPACE_NAME}-8082.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
PAYMENTS_SERVICE_URL=https://${CODESPACE_NAME}-8083.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
STOCK_SERVICE_URL=https://${CODESPACE_NAME}-8084.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}

# Environment
ENVIRONMENT=codespaces
YOUTUBE_API_KEY=AIzaSyA_cOSojH1AVc4phKoP14cYPkGUpdWhpuQ
YOUTUBE_CHANNEL_ID=@Ritrix252
EOF

    # Update application.yml files for Codespaces
    for service_dir in */; do
        if [ -d "$service_dir" ] && [[ "$service_dir" == *-service/ ]]; then
            service_name=${service_dir%/}
            yml_file="$service_dir/src/main/resources/application.yml"
            
            if [ -f "$yml_file" ]; then
                echo "📝 Updating $yml_file for Codespaces"
                
                # Create temporary file with updated configuration
                cat > "${yml_file}.tmp" << EOF
spring:
  application:
    name: $service_name
  
  datasource:
    url: $DB_URL
    username: gamestore_user
    password: gamestore_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  
  profiles:
    active: codespaces
  
  session:
    store-type: none
  
  h2:
    console:
      enabled: true

server:
  port: ${service_ports[$service_name]}

logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG
EOF
                
                # Replace the original file
                mv "${yml_file}.tmp" "$yml_file"
            fi
        fi
    done

else
    echo "🏠 Detected local development environment"
    
    # Set local URLs
    DB_HOST="localhost:3306"
    DB_URL="jdbc:mysql://localhost:3306/Game_Store_System?createDatabaseIfNotExist=true"
    ENVIRONMENT="local"
    
    # Create .env file for local development
    cat > .env << EOF
# Backend Environment Variables for Local Development
# Auto-generated by setup_backend_env.sh

# Database Configuration
DB_HOST=$DB_HOST
DB_URL=$DB_URL
DB_USERNAME=gamestore_user
DB_PASSWORD=gamestore_pass

# Service URLs
ACCOUNTS_SERVICE_URL=http://localhost:8080
PRODUCTS_SERVICE_URL=http://localhost:8081
ORDERS_SERVICE_URL=http://localhost:8082
PAYMENTS_SERVICE_URL=http://localhost:8083
STOCK_SERVICE_URL=http://localhost:8084

# Environment
ENVIRONMENT=local
YOUTUBE_API_KEY=AIzaSyA_cOSojH1AVc4phKoP14cYPkGUpdWhpuQ
YOUTUBE_CHANNEL_ID=@Ritrix252
EOF

    # Update application.yml files for local development
    for service_dir in */; do
        if [ -d "$service_dir" ] && [[ "$service_dir" == *-service/ ]]; then
            service_name=${service_dir%/}
            yml_file="$service_dir/src/main/resources/application.yml"
            
            if [ -f "$yml_file" ]; then
                echo "📝 Updating $yml_file for local development"
                
                # Create temporary file with updated configuration
                cat > "${yml_file}.tmp" << EOF
spring:
  application:
    name: $service_name
  
  datasource:
    url: $DB_URL
    username: gamestore_user
    password: gamestore_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  
  profiles:
    active: local
  
  session:
    store-type: none
  
  h2:
    console:
      enabled: true

server:
  port: ${service_ports[$service_name]}

logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG
EOF
                
                # Replace the original file
                mv "${yml_file}.tmp" "$yml_file"
            fi
        fi
    done
fi

# Create docker-compose override file
if [ "$ENVIRONMENT" = "codespaces" ]; then
    cat > docker-compose.override.yml << EOF
version: '3.8'
services:
  accounts-service:
    environment:
      - SPRING_PROFILES_ACTIVE=codespaces
      - DB_URL=$DB_URL
    ports:
      - "8080:8080"
  
  products-service:
    environment:
      - SPRING_PROFILES_ACTIVE=codespaces
      - DB_URL=$DB_URL
    ports:
      - "8081:8081"
  
  orders-service:
    environment:
      - SPRING_PROFILES_ACTIVE=codespaces
      - DB_URL=$DB_URL
    ports:
      - "8082:8082"
EOF
else
    cat > docker-compose.override.yml << EOF
version: '3.8'
services:
  accounts-service:
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8080:8080"
  
  products-service:
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8081:8081"
  
  orders-service:
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8082:8082"
EOF
fi

echo "✅ Backend environment setup complete!"
echo "📋 Configuration summary:"
echo "  Environment: $ENVIRONMENT"
echo "  Database: $DB_HOST"
echo "  Main service port: 8080"

echo ""
echo "🚀 Next steps:"
echo "  1. Start your database server"
echo "  2. Run: ./gradlew bootRun (for individual services)"
echo "  3. Or use: docker-compose up (for all services)"
