#!/usr/bin/env python3
"""
Environment setup script for AI Recommendation Service
Automatically detects if running in GitHub Codespaces and sets appropriate URLs
"""

import os
import shutil

def setup_environment():
    """Setup environment variables based on current environment"""
    
    # Check if we're in GitHub Codespaces
    is_codespaces = os.getenv('CODESPACES') == 'true'
    codespace_name = os.getenv('CODESPACE_NAME')
    github_codespaces_port_forwarding_domain = os.getenv('GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN', 'preview.app.github.dev')
    
    # Check if we're inside a devcontainer
    in_devcontainer = os.getenv('REMOTE_CONTAINERS') or os.path.exists('/.dockerenv')
    
    # Copy .env.example to .env if .env doesn't exist
    if not os.path.exists('.env'):
        if os.path.exists('.env.example'):
            shutil.copy('.env.example', '.env')
            print("Created .env from .env.example")
        else:
            print("Warning: .env.example not found")
            return
    
    # Read current .env file
    env_vars = {}
    if os.path.exists('.env'):
        with open('.env', 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key.strip()] = value.strip()
    
    # Set database URL based on environment
    db_user = os.getenv('DB_USERNAME', 'gamestore_user')
    db_pass = os.getenv('DB_PASSWORD', 'your_db_password_here')
    
    if in_devcontainer:
        # Inside devcontainer - always use 'db' service name
        print("📦 Detected devcontainer environment - using 'db' service for database")
        database_host = "db"
        database_url = f"mysql+pymysql://{db_user}:{db_pass}@{database_host}:3306/Game_Store_System"
    else:
        # Outside devcontainer - use localhost
        print("🏠 Outside devcontainer - using localhost for database")
        database_host = "localhost"
        database_url = f"mysql+pymysql://{db_user}:{db_pass}@{database_host}:3306/Game_Store_System"
    
    # Set backend URL based on Codespaces or local
    if is_codespaces and codespace_name:
        # GitHub Codespaces environment
        backend_url = f"https://{codespace_name}-8080.{github_codespaces_port_forwarding_domain}"
        print(f"🚀 Detected GitHub Codespaces environment: {codespace_name}")
        print(f"Backend URL: {backend_url}")
        env_vars['ENVIRONMENT'] = 'codespaces'
    else:
        # Local development environment
        backend_url = 'http://localhost:8080'
        print(f"Backend URL: {backend_url}")
        env_vars['ENVIRONMENT'] = 'local'
    
    # Update environment variables
    env_vars['BACKEND_API_URL'] = backend_url
    env_vars['DATABASE_URL'] = database_url
    
    # Write updated .env file
    with open('.env', 'w') as f:
        f.write("# Environment variables for AI Recommendation Service\n")
        f.write("# Auto-generated by setup_env.py\n\n")
        
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    print("Environment setup complete!")
    print(f"Backend API URL: {env_vars.get('BACKEND_API_URL')}")
    print(f"Environment: {env_vars.get('ENVIRONMENT')}")

if __name__ == "__main__":
    setup_environment()
