spring:
  application:
    name: orderitems-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/Game_Store_System?createDatabaseIfNotExist=true
    username: gamestore_user
    password: gamestore_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8084

logging:
  level:
    com.example.orderitems: DEBUG
