#!/usr/bin/env python3
"""
Environment setup script for AI Recommendation Service
Automatically detects if running in GitHub Codespaces and sets appropriate URLs
"""

import os
import shutil

def setup_environment():
    """Setup environment variables based on current environment"""
    
    # Check if we're in GitHub Codespaces
    is_codespaces = os.getenv('CODESPACES') == 'true'
    codespace_name = os.getenv('CODESPACE_NAME')
    github_codespaces_port_forwarding_domain = os.getenv('GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN')
    
    # Copy .env.example to .env if .env doesn't exist
    if not os.path.exists('.env'):
        if os.path.exists('.env.example'):
            shutil.copy('.env.example', '.env')
            print("Created .env from .env.example")
        else:
            print("Warning: .env.example not found")
            return
    
    # Read current .env file
    env_vars = {}
    if os.path.exists('.env'):
        with open('.env', 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key.strip()] = value.strip()
    
    # Set dynamic URLs based on environment
    if is_codespaces and codespace_name and github_codespaces_port_forwarding_domain:
        # GitHub Codespaces environment
        backend_url = f"https://{codespace_name}-8080.{github_codespaces_port_forwarding_domain}"
        database_host = f"{codespace_name}-3306.{github_codespaces_port_forwarding_domain}"
        
        print(f"Detected GitHub Codespaces environment: {codespace_name}")
        print(f"Backend URL: {backend_url}")
        
        # Update environment variables
        env_vars['BACKEND_API_URL'] = backend_url
        env_vars['DATABASE_URL'] = f"mysql+pymysql://user:password@{database_host}/game_music_store"
        env_vars['ENVIRONMENT'] = 'codespaces'
        
        # Preserve existing API keys if they exist
        if 'YOUTUBE_API_KEY' not in env_vars or env_vars['YOUTUBE_API_KEY'] == 'your_youtube_api_key_here':
            env_vars['YOUTUBE_API_KEY'] = 'AIzaSyA_cOSojH1AVc4phKoP14cYPkGUpdWhpuQ'
        if 'YOUTUBE_CHANNEL_ID' not in env_vars:
            env_vars['YOUTUBE_CHANNEL_ID'] = '@Ritrix252'
        
    else:
        # Local development environment
        print("Detected local development environment")
        env_vars['BACKEND_API_URL'] = env_vars.get('BACKEND_API_URL', 'http://localhost:8080')
        env_vars['DATABASE_URL'] = env_vars.get('DATABASE_URL', 'mysql+pymysql://user:password@localhost:3306/game_music_store')
        env_vars['ENVIRONMENT'] = 'local'
        
        # Preserve existing API keys if they exist
        if 'YOUTUBE_API_KEY' not in env_vars or env_vars['YOUTUBE_API_KEY'] == 'your_youtube_api_key_here':
            env_vars['YOUTUBE_API_KEY'] = 'AIzaSyA_cOSojH1AVc4phKoP14cYPkGUpdWhpuQ'
        if 'YOUTUBE_CHANNEL_ID' not in env_vars:
            env_vars['YOUTUBE_CHANNEL_ID'] = '@Ritrix252'
    
    # Write updated .env file
    with open('.env', 'w') as f:
        f.write("# Environment variables for AI Recommendation Service\n")
        f.write("# Auto-generated by setup_env.py\n\n")
        
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    print("Environment setup complete!")
    print(f"Backend API URL: {env_vars.get('BACKEND_API_URL')}")
    print(f"Environment: {env_vars.get('ENVIRONMENT')}")

if __name__ == "__main__":
    setup_environment()
